services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiz-whiz-app:latest
    container_name: quiz-whiz-web
    restart: unless-stopped
    ports:
      - "4516:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
networks:
  default:
    external: true
    name: npm-network
