services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiz-whiz-app:latest
    container_name: quiz-whiz-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
